### ISSUE TITLE
Proposal: automatic Component and System registration

### ISSUE THREAD

**Issue by jcarlosrc** [GodotECS/godex#100]
It would be nice to have a simpler component and systema registration/removal.

I would propose the Component and System registration to be automatic. I mean, the posibility to choose any resource .gd script as a System or Component without the needing of first registering it as one to the ECS world. The registration would take place behind the scenes after the "ok" or double click.

Also, a list of current registered Components and Systems in the editor to remove one if wanted.

**Comment by AndreaCatania** [comment]
@jcarlosrc This would be nice, I agree. We need to research a way to detect resource creation. If we can detect that, we can build the `Component` / `System` list easily. Not sure if Godot has such signal already, TBH.

**Comment by AndreaCatania** [comment]
Done :)
