### ISSUE TITLE
Add a description to README.md that explains how to download Actions binary

### ISSUE THREAD

**Issue by sairam4123** [GodotECS/godex#105]
Hi, I am Sairam, I am working on OpenSkyCity, and I wanted to take a look into Godex, but since my computer is too bad, I can't build the godot. I would like to get a download link of the build.

Thank you.

**Comment by AndreaCatania** [comment]
You can download the Godex binary from the Action, already. Try follow this:

![download-godex-binary](https://user-images.githubusercontent.com/8342599/109544641-19cf5c80-7ac8-11eb-8b28-f678f9408c85.gif)

**Comment by sairam4123** [comment]
Nice thanks!

**Comment by AndreaCatania** [comment]
Welcome!
I'm reopening it so I've a reminder that I've to improve the docs.
