### ISSUE TITLE
Dropdown Arrow Should Rotate When Component Is Open

### ISSUE THREAD

**Issue by TCROC** [GodotECS/godex#146]
![image](https://user-images.githubusercontent.com/24307049/115433562-b7483200-a1d5-11eb-9e45-7a192ee9fecf.png)

The ``>`` arrow should rotate to ``v`` when the component is open.

Just a small visual improvement suggestion.  :)

**Comment by AndreaCatania** [comment]
Thanks for the issue, checking it seems related to godot editor since this is the same for the node inspector sections. A future godot update will fix this automatically.

For now keep this issue open is a good way to keep track of it.

**Comment by TCROC** [comment]
Is this being tracked by Godot yet?  Or should I open it up over there as well?

**Comment by AndreaCatania** [comment]
Not sure about that, probably worth add it there too, yes

**Comment by AndreaCatania** [comment]
Fixed by: #195
