### ISSUE TITLE
Godex does not compile using latest Godot master branch

### ISSUE THREAD

**Issue by RicardRC** [GodotECS/godex#248]
godex\modules\godot\editor_plugins\components_gizmo_3d.h(4): fatal error C1083: Cannot open include file: 'editor/node_3d_editor_gizmos.h': No such file or directory

Fixing it (changing to editor/plugins/node_3d_editor_gizmos.h)

Gives mote errors. Fixing those gives even more errors...

**Comment by AndreaCatania** [comment]
Can you please paste some of those errors here? So I will make an idea of those.

**Comment by RicardRC** [comment]
The first one was because the name of the godot gizmo clase used as base class has changed. Fixing that, I don't have them right now, but if I remember correctly it couldn't find many of the gizmo functions, as if the object hierarchy was somehow broken: "override did not override any base function". Couldn't figure out what went wrong, as includes and all semed fine.
