### ISSUE TITLE
Copy customizable_iterator branch of godot to GodotECS

### ISSUE THREAD

**Issue by fire** [GodotECS/godex#25]
https://github.com/AndreaCatania/godot/tree/customizable_iterator should be in this organization.

**Comment by AndreaCatania** [comment]
We have this patch here: https://github.com/GodotECS/godex/blob/main/patches/add_custom_iterator.patch but I agree. How would we bring this in? (Fork godot and cherry-pick the commit?)

**Comment by fire** [comment]
Fork godot engine and then duplicate the branch is the standard way.

**Comment by AndreaCatania** [comment]
I think it make sense, yes.

**Comment by fire** [comment]
Done.
