### ISSUE TITLE
Parent ECS entities

### ISSUE THREAD

**Issue by fire** [GodotECS/godex#28]
### Describe the project you are working on
3D Game

### Describe the problem or limitation you are having in your project
Unable to recreate parent to child transform. So I'm not able to write a scene root to packed scene converter.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Allow the creation of a parent to child relationship spatially.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

The component contains the parent entity ID. A system resolve those transforms, before updating the meshes position.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
Not trivial done by a few lines of script.

### Is there a reason why this should be core and not an add-on in the asset library?
Could be a gd script component.

**Comment by AndreaCatania** [comment]
I've added the `Child` component and a mechanism to propagate automatically the hierarchy: https://github.com/GodotECS/godex/pull/55 

However, the mechanism to handle the hierarchy system that handles the transformations at runtime is still missing: This mean that in editor the composed scene is fine but at runtime the transformation is not properly solved.
