### ISSUE TITLE
Expose ComponentEvent to scripting

### ISSUE THREAD

**Issue by AndreaCatania** [GodotECS/godex#44]
There is a new `Component` type, which name is `ComponentEvent`.
It represent an `Event` in `Godex`: The difference to a standard `Component` is that it's automatically removed from the `World` at the end of the processing.

You can see how to use it, in C++, https://github.com/GodotECS/godex/blob/main/tests/test_ecs_system.h#L532-L564 `TEST_CASE("[Modules][ECS] Test event mechanism.") {`

**Expose it to Scripting.**

**Comment by RicardRC** [comment]
(The lines have moved, and the pointer no longer aims to the correct code section!)

**Comment by AndreaCatania** [comment]
Nice catch, fixed.

**Comment by AndreaCatania** [comment]
I've removed the `ComponentEvent` in favor of `Event` in this https://github.com/GodotECS/godex/pull/199. Everything is already exposed. 

wiki: https://github.com/GodotECS/godex/wiki/Events
