### ISSUE TITLE
Patch cannot be applied in a Windows build

### ISSUE THREAD

**Issue by carlos-ramos-73** [GodotECS/godex#80]
When applying the patch in a windows build, the git throws errors that the patch does not apply:
`git apply modules/godex/patches/add_custom_iterator.patch`
`error: patch failed: SConstruct:543`
`error: SConstruct: patch does not apply`
`error: patch failed: core/config/engine.h:88`
`error: core/config/engine.h: patch does not apply`
`error: patch failed: main/main.cpp:1284`
`error: main/main.cpp: patch does not apply`
`error: patch failed: main/main.h:54`
`error: main/main.h: patch does not apply`

I think this might due to linespacing formatting issues between unix and windows systems.
The following command successfully applied the patch with no errors:
`git apply --ignore-space-change --ignore-whitespace modules/godex/patches/add_custom_iterator.patch`

**BUT** will not allow it to build successfully:

`C:\Users\Carlos\Documents\Godot\godot\modules\godex\iterators\../storage/storage.h(206): error C2663: 'MeshComponent::set': 2 overloads have no legal conversion for 'this' pointer`

`C:\Users\Carlos\Documents\Godot\godot\modules\godex\iterators\../storage/storage.h(201): note: while compiling class template member 
function 'void Storage<const C>::insert_dynamic(EntityID,const Dictionary &)'
        with
        [
            C=MeshComponent
        ]`

`C:\Users\Carlos\Documents\Godot\godot\modules\godex\systems\../iterators/query.h(201): note: see reference to class template instantiation 'Storage<const C>' being compiled
        with
        [
            C=MeshComponent
        ]`

`C:\Users\Carlos\Documents\Godot\godot\modules\godex\systems\../iterators/query.h(195): note: while compiling class template member function 'bool QueryStorage<const MeshComponent,const TransformComponent>::has_data(EntityID) const'`

`C:\Users\Carlos\Documents\Godot\godot\modules\godex\systems\../iterators/query.h(263): note: see reference to function template instantiation 'bool QueryStorage<const MeshComponent,const TransformComponent>::has_data(EntityID) const' being compiled`

`C:\Users\Carlos\Documents\Godot\godot\modules\godex\systems\../iterators/query.h(230): note: see reference to class template instantiation 'QueryStorage<const MeshComponent,const TransformComponent>' being compiled`

`C:\Users\Carlos\Documents\Godot\godot\modules\godex\systems/system_builder.h(87): note: see reference to class template instantiation 'Query<const MeshComponent,const TransformComponent>' being compiled`

`C:\Users\Carlos\Documents\Godot\godot\modules\godex\systems\system_exe_funcs.gen.h(12): note: see reference to class template instantiation 'SystemBuilder::DataFetcher<P1>' being compiled
        with
        [
            P1=Query<const MeshComponent,const TransformComponent> &
        ]
modules\godex\register_types.cpp(113): note: see reference to function template instantiation 'void SystemBuilder::system_exec_func<RenderingServerDatabag*,Query<const MeshComponent,const TransformComponent>&>(World *,void (__cdecl *)(P0,P1))' being compiled        
        with
        [
            P0=RenderingServerDatabag *,
            P1=Query<const MeshComponent,const TransformComponent> &
        ]`

`scons: *** [modules\godex\register_types.windows.tools.64.obj] Error 2`

`scons: building terminated because of errors.`

**Comment by carlos-ramos-73** [comment]
After comparing files to both linux and windows builds, I noticed they are identical.
The patch was successfully applied. 
I think this is more of a scons linking issue.
I see similar reported issues like this in Godot's repo:
https://github.com/godotengine/godot/issues/5182

I will look more into how to compile

**Comment by AndreaCatania** [comment]
I've just updated the wiki adding `--ignore-space-change --ignore-whitespace`.

**Comment by carlos-ramos-73** [comment]
Just adding some notes before I forget,
I still have not managed to compile on Windows correctly.

**Attempted**
- Compiling it under Visual Studio 2019 Command Prompt
- Compiling it in x32 and x64
- Trying different scons parameters, verbose was of no help
- Moving the module externally and trying to compile using custom_modules
- Cleaning scons and try to compile after a clean
- Running scons as administrator
- Reinstalled requirements to latest, ie. python, scons, VS 2019 (with C++ support)
- Restarting the system

**Need to Test**
- mingw compilation with yasm
- Downgrading scons version
- Actually trying to fix the compiler error

**Comment by carlos-ramos-73** [comment]
The reason why I haven't looked to deep into the code is that I find it crazy the scons on linux doesn't throw anything, yet windows throws a fit -.-

**Regarding the Error**
The compiler error is due to running `insert_dynamic()` inside `storage.h`. The compiler uses the template to attempt to create the function for `const MeshComponent` but fails due to `2 overloads have no legal conversion for 'this' pointer`. I can only guess this might have to do with using the `const` keyword somewhere here.

Again I haven't looked too much into the code, nor do I know if this is truly why it doesn't compile on Windows

**Comment by AndreaCatania** [comment]
This issue should be already fixed, can you please confirm it please?

**Comment by bitmammoth** [comment]
I just had what looks like this same error when compiling on windows. 

I used git submodule add https://github.com/GodotECS/godex.git modules/godex and git apply modules/godex/patches/add_custom_iterator.patch --reject --ignore-space-change --ignore-whitespace.

![image](https://user-images.githubusercontent.com/21980039/108588768-beef7580-730f-11eb-804b-a67fbab3d831.png)

**Comment by AndreaCatania** [comment]
That's weird, however you can directly pull this branch https://github.com/GodotECS/godot/tree/godex_version. It's the godot commit `ae6b2d6edc76de347ccb11c4608b6e8174e1884f` with the patch already applied. The CI is using that godot version.

**Comment by carlos-ramos-73** [comment]
I can confirm working using ae6b2d6edc76de347ccb11c4608b6e8174e1884f and applying patch.
Also working with https://github.com/GodotECS/godot/tree/godex_version , which is the same thing.

I can confirm **NOT Working** with Godot latest main branch, which at the time of writing is `d4d753552495dda0eefcdd69228eb4ed4ddc5447`

Scons Error:
`C:\Users\Carlos\Documents\Godot\godot\modules\godex\godot/editor_plugins/editor_world_ecs.h(137): error C3668: 'EditorWorldECS::_changed_callback': method with override specifier 'override' did not override any base class methods`

`C:\Users\Carlos\Documents\Godot\godot\modules\godex\godot/editor_plugins/entity_editor_plugin.h(42): error C3668: 'EntityEditor::_changed_callback': method with override specifier 'override' did not override any base class methods`

`scons: *** [modules\godex\register_types.windows.tools.64.obj] Error 2`

`scons: building terminated because of errors.`

@bitmammoth Is the cause of your errors because you used godot's latest as well?

**Comment by bitmammoth** [comment]
> 
> 
> I can confirm working using `ae6b2d6edc76de347ccb11c4608b6e8174e1884f` and applying patch.
> Also working with https://github.com/GodotECS/godot/tree/godex_version , which is the same thing.
> 
> I can confirm **NOT Working** with Godot latest main branch, which at the time of writing is `d4d753552495dda0eefcdd69228eb4ed4ddc5447`
> 
> Scons Error:
> `C:\Users\Carlos\Documents\Godot\godot\modules\godex\godot/editor_plugins/editor_world_ecs.h(137): error C3668: 'EditorWorldECS::_changed_callback': method with override specifier 'override' did not override any base class methods`
> 
> `C:\Users\Carlos\Documents\Godot\godot\modules\godex\godot/editor_plugins/entity_editor_plugin.h(42): error C3668: 'EntityEditor::_changed_callback': method with override specifier 'override' did not override any base class methods`
> 
> `scons: *** [modules\godex\register_types.windows.tools.64.obj] Error 2`
> 
> `scons: building terminated because of errors.`
> 
> @bitmammoth Is the cause of your errors because you used godot's latest as well?

Yes, I believe so, I will try to compile from an earlier version as well to try and confirm.

**Comment by carlos-ramos-73** [comment]
Closing because patch can be applied successfully and latest Godex can build with tested Godot master branch `ae6b2d6edc76de347ccb11c4608b6e8174e1884f `. We can wait for the patch to be synced with current Godot master branch in a few weeks, #90
`"Godex aims to be use in the Godot master. If it doesn't compile with the current master it's fine. I plan to re-sync it in few weeks."`
