### ISSUE TITLE
LLVM Compilation Error

### ISSUE THREAD

**Issue by jcarlosrc** [GodotECS/godex#90]
I am getting the following compilation error message:

_modules/godex/components/../systems/../iterators/query.h: In member function 'std::tuple<Batch<typename remove_filter<Cs>::type>...> QueryStorage<Cs>::get(EntityID, Space) const':
modules/godex/components/../systems/../iterators/query.h:39:103: error: cannot deduce template arguments for 'tuple' from ()
  std::tuple<Batch<remove_filter_t<Cs>>...> get(EntityID p_id, Space p_mode) const { return std::tuple(); }
                                                                                                       ^
scons: *** [modules/godex/components/child.linuxbsd.tools.64.o] Error 1
scons: building terminated because of errors._

I am using latest stable Godot and Godex versions and compiling as described in the wiki.

Any idea to fix it? Thanks.

**Comment by AndreaCatania** [comment]
Are you using GCC? Which version do you have? make sure to use the last one.

This is mine:
```
[andrea@pc-13 ~]$ gcc --version
gcc (GCC) 10.2.1 20201125 (Red Hat 10.2.1-9)
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by jcarlosrc** [comment]
Effectively, I was using gcc-8. Now I switched to 10.2.0

_gcc --version
gcc (Ubuntu 10.2.0-5ubuntu1~20.04) 10.2.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE._

However, it does not seem to recognize it:

_scons: Reading SConscript files ...
Enabling ALSA
Enabling PulseAudio
Enabling udev support
Couldn't parse CXX environment variable to infer compiler version.
Detected GCC version older than 7, which does not fully support C++17. Supported versions are GCC 7, 9 and later. Use a newer GCC version, or Clang 6 or later by passing "use_llvm=yes" to the SCons command line._

When using use _llvm=yes_ option, I get the following compilation error:

_[ 43%] Compiling ==> modules/godex/components/child.cpp
In file included from modules/godex/components/child.cpp:1:
In file included from modules/godex/components/child.h:3:
modules/godex/components/component.h:102:39: error: 'target' is a private member of 'DataAccessor'
                return static_cast<const T *>(comp->target);
                                                    ^
modules/godex/components/../systems/../iterators/../world/../ecs_types.h:460:8: note: declared private here
        void *target = nullptr;
              ^
1 error generated.
scons: *** [modules/godex/components/child.linuxbsd.tools.64.llvm.o] Error 1
scons: building terminated because of errors._

**Comment by AndreaCatania** [comment]
I'll check llvm, thanks.

**Comment by jcarlosrc** [comment]
Actually this seems to be an issue with the regular Godot compilation process. So I should post there. Thanks.

**Comment by jcarlosrc** [comment]
I managed to get gcc to work. Get the same error as llvm as expected. Using gcc-10 and g++-10 versions.

_In file included from modules/godex/components/child.cpp:1:
In file included from modules/godex/components/child.h:3:
modules/godex/components/component.h: 100 :39: error: 'target' is a private member of 'DataAccessor'
                return static_cast<const T *>(comp->target);
                                                    ^
modules/godex/components/../systems/../iterators/../world/../ecs_types.h:458:8: note: declared private here
        void *target = nullptr;
              ^
1 error generated.
scons: *** [modules/godex/components/child.linuxbsd.tools.64.llvm.o] Error 1
scons: building terminated because of errors._

**Comment by jcarlosrc** [comment]
I got GCC 10 to work. Now I get the following error

_[ 44%] Compiling ==> modules/godex/register_types.cpp
In file included from modules/godex/register_types.cpp:17:
modules/godex/godot/editor_plugins/editor_world_ecs.h:137:7: error: 'void EditorWorldECS::_changed_callback(Object*, const char*)' marked 'override', but does not override
  137 |  void _changed_callback(Object *p_changed, const char *p_prop) override;
      |       ^~~~~~~~~~~~~~~~~
In file included from modules/godex/register_types.cpp:18:
modules/godex/godot/editor_plugins/entity_editor_plugin.h:42:15: error: 'virtual void EntityEditor::_changed_callback(Object*, const char*)' marked 'override', but does not override
   42 |  virtual void _changed_callback(Object *p_changed, const char *p_prop) override;
      |               ^~~~~~~~~~~~~~~~~
In file included from modules/godex/godot/editor_plugins/components_gizmo_3d.h:3,
                 from modules/godex/register_types.cpp:16:
modules/godex/godot/editor_plugins/../nodes/entity.h: In instantiation of 'void EntityInternal<C>::update_components_data() [with C = Entity3D]':
modules/godex/godot/editor_plugins/../nodes/entity.h:202:33:   required from here
modules/godex/godot/editor_plugins/../nodes/entity.h:745:9: error: 'class Entity3D' has no member named '_change_notify'
  745 |  owner->_change_notify("components_data");
      |  ~~~~~~~^~~~~~~~~~~~~~
modules/godex/godot/editor_plugins/../nodes/entity.h: In instantiation of 'void EntityInternal<C>::update_components_data() [with C = Entity2D]':
modules/godex/godot/editor_plugins/../nodes/entity.h:293:33:   required from here
modules/godex/godot/editor_plugins/../nodes/entity.h:745:9: error: 'class Entity2D' has no member named '_change_notify'
scons: *** [modules/godex/register_types.linuxbsd.tools.64.o] Error 1
scons: building terminated because of errors._

**Comment by AndreaCatania** [comment]
Is your godot version based on the commit `ae6b2d6edc76de347ccb11c4608b6e8174e1884f`? Probably this is the issue.

You can try to use this version: https://github.com/GodotECS/godot/tree/godex_version it's based on the above commit and has the godex patch already applied. In this case you can just clone it, and compile it with godex; it should just work.

**Comment by TCROC** [comment]
It may be related to this, but I found that the patch cannot be applied to Godot's current master branch which also inherently results in the compilation error.

Master is under active development which I imagine is hard to maintain compatibility for.  I imagine Godex will be supported for official Godot releases?  Or what is the plan there?

**Comment by AndreaCatania** [comment]
@TCROC Yes, Godex aims to be use in the Godot master. If it doesn't compile with the current master it's fine. I plan to re-sync it in few weeks.

**Comment by jcarlosrc** [comment]
To confirm that the Godot version at https://github.com/GodotECS/godot/tree/godex_version godot version compiles with no problems, thanks.

**Comment by AndreaCatania** [comment]
@jcarlosrc Feel free to close this if it also compiles with LLVM.
